# Generated by Django 4.1.7 on 2023-04-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idBacklog', models.AutoField(help_text='ID único para este Proyecto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del proyecto', max_length=50)),
                ('descripcion', models.CharField(help_text='Ingrese una descripcion para el proyecto', max_length=200)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('i', 'Iniciado'), ('f', 'Finalizado'), ('p', 'Pospuesto')], default='i', help_text='Estado del proyecto', max_length=1)),
                ('miembros', models.ManyToManyField(related_name='projects_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('idUserStory', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('storyPoints', models.IntegerField(default=0)),
                ('hecho', models.CharField(max_length=100)),
                ('prioridad', models.CharField(blank=True, choices=[('1', 'Mayor'), ('2', 'Media'), ('3', 'Menor')], default='2', help_text='Prioridad de la tarea', max_length=1)),
                ('estado', models.CharField(blank=True, choices=[('I', 'To do'), ('D', 'Doing'), ('T', 'Done'), ('C', 'Cancelled')], default='I', help_text='Estado de la tarea', max_length=1)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('idSprintBacklog', models.AutoField(help_text='ID único para este Sprint', primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('idBacklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.proyecto')),
            ],
        ),
    ]
