# Generated by Django 4.1.7 on 2023-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rol_remove_proyecto_miembros_usuarioproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('i', 'Iniciado'), ('f', 'Finalizado'), ('p', 'Pospuesto')], default='Iniciado', help_text='Estado del proyecto', max_length=1),
        ),
    ]
