# Generated by Django 4.1.7 on 2023-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Iniciado', 'Iniciado'), ('Finaliza', 'Finalizado'), ('Pospuesto', 'Pospuesto')], default='Iniciado', help_text='Estado del proyecto', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.CharField(blank=True, choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='I', help_text='Estado de la tarea', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Mayor', 'Mayor'), ('Media', 'Media'), ('Menor', 'Menor')], default='2', help_text='Prioridad de la tarea', max_length=10),
        ),
    ]
