# Generated by Django 4.1.7 on 2023-05-06 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_proyecto_estado_alter_userstory_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sprint')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.userstory')),
            ],
        ),
    ]
